### ISSUE TITLE
argocd-notifications-cm sed work

### ISSUE THREAD

**Issue by agardnerIT** [henrikrexed/openfeature#8]
`argocd/argocd-notifications-cm.yaml` template should be:

```
apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
stringData:
  dt-env: "DT_TENANT_TO_REPLACE"
  dt-api-token: "DT_TOKEN_TO_REPLACE"
  webhook-env: "WEBSOCKET_URL_TO_REPLACE"
type: Opaque
```

Then instructions for `sed` when working with `argocd/argocd-notifications-cm.yaml` should be:

```
# User to set the variable below
WEBSOCKET_URL=https://webhook.site/abcd1234-1234-abcd-abcd-1234aaaa2341

sed -i "s,WEBSOCKET_URL_TO_REPLACE,$WEBSOCKET_URL," argocd/argocd-notifications-secret.yaml
sed -i "s,DT_TENANT_TO_REPLACE,$DT_TENANT_URL," argocd/argocd-notifications-secret.yaml
sed -i "s,DT_TOKEN_TO_REPLACE,$DATA_INGEST_TOKEN," argocd/argocd-notifications-secret.yaml
kubectl -n argocd apply -f argocd/argocd-notifications-secret.yaml

# git restore to remove sensitive info and prevent accidental commits of sensitive keys
git restore argocd/*
kubectl -n argocd apply -f argocd/notifications-cm.yaml
```
